#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// build-html.mjs — stitches engine.js + vcf-design-studio-v6.jsx into the
// shipped single-file vcf-design-studio-v6.html artifact.
//
// The browser runtime stays build-free (React/Tailwind/Babel from CDNs).
// This script is dev-only: it just concatenates sources into the HTML shell.
//
// Pipeline:
//   1. Read engine.js — the pure sizing engine.
//   2. Read the .jsx — React components that consume window.VcfEngine.
//   3. Transform the .jsx: strip the `import` line, pull React hooks off the
//      global React, and strip the `export default` on VcfFleetSizer.
//   4. Assemble the HTML with two inline <script> blocks:
//        a) plain <script> for engine.js (no Babel transform needed)
//        b) <script type="text/babel"> for the JSX + mount line
//
// Exports `buildHtml()` so verify-html-sync.mjs can call it without touching
// the filesystem.
// ─────────────────────────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const ENGINE_SRC = path.join(ROOT, "engine.js");
const JSX_SRC    = path.join(ROOT, "vcf-design-studio-v6.jsx");
const HTML_OUT   = path.join(ROOT, "vcf-design-studio-v6.html");

export function buildHtml() {
  const engine = fs.readFileSync(ENGINE_SRC, "utf8").replace(/\r\n/g, "\n");
  const jsxRaw = fs.readFileSync(JSX_SRC, "utf8").replace(/\r\n/g, "\n");

  let jsx = jsxRaw;

  const importRe = /^import\s*\{\s*([^}]+?)\s*\}\s*from\s*["']react["'];\s*$/m;
  if (!importRe.test(jsx)) {
    throw new Error("build-html: expected React named-imports line not found in JSX source");
  }
  jsx = jsx.replace(importRe, (_m, names) => {
    const clean = names.split(",").map((s) => s.trim()).filter(Boolean).join(", ");
    return `const { ${clean} } = React;`;
  });

  const engineRe = /\(typeof window !== "undefined" \? window\.VcfEngine : require\("\.\/engine\.js"\)\)/;
  if (!engineRe.test(jsx)) {
    throw new Error("build-html: expected window.VcfEngine / require() fallback not found in JSX source");
  }
  jsx = jsx.replace(engineRe, "window.VcfEngine");

  const exportRe = /^export default function VcfFleetSizer\(\) \{/m;
  if (!exportRe.test(jsx)) {
    throw new Error("build-html: expected `export default function VcfFleetSizer` declaration not found");
  }
  jsx = jsx.replace(exportRe, "function VcfFleetSizer() {");

  const MOUNT = `
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<VcfFleetSizer />);`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>VCF Design Studio — v6</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet" />
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body { margin: 0; padding: 0; background: #f8fafc; }
    .font-serif { font-family: 'Inter', system-ui, sans-serif !important; font-weight: 600 !important; }
    .font-mono  { font-family: 'IBM Plex Mono', ui-monospace, monospace !important; }
    input[type=number]::-webkit-inner-spin-button { opacity: 0.3; }
    select option { background: #fff; }
  </style>
</head>
<body>
  <!--
    This file is generated by scripts/build-html.mjs from engine.js and
    vcf-design-studio-v6.jsx. Do not hand-edit — run \`npm run build-html\`.
  -->
  <div id="root"></div>
  <script>
${engine}
  </script>
  <script type="text/babel" data-type="module">
${jsx}${MOUNT}
  </script>
</body>
</html>
`;
}

export const OUTPUT_PATH = HTML_OUT;

// CLI entrypoint — only runs when invoked directly, not when imported.
if (import.meta.url === `file://${process.argv[1]}` ||
    import.meta.url === `file:///${process.argv[1].replace(/\\/g, "/")}`) {
  const html = buildHtml();
  fs.writeFileSync(HTML_OUT, html, "utf8");
  console.log(`build-html: wrote ${path.basename(HTML_OUT)} (${html.split("\n").length} lines)`);
}
